name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_prettier:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["nema-client", "nema-server"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Change to target directory
        run: cd ${{ matrix.folder }}

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn prettier-check
